### ISSUE TITLE
Loading time 

### ISSUE THREAD

**Issue by MartinLichtblau** [foray1010/Popup-my-Bookmarks#7] opened 2015-08-07 15:39 UTC
The loading time of the popup is not extremely high but if you compare it to Chrome's default bookmark manger it's just slow. 

Since speed or better say responsiveness is very important for users. Especially for a tool like PMB which you use many many times whith the goal to find and open the bookmark-link quickly. Don't get me wrong, when it's open it's very responsive and also the search runs great. But when clicking on PBM or openning it with a shortcut it takes it's time to respond.  Would be great if this could be improved! :+1: 

Here's a hint how to achieve that http://stackoverflow.com/questions/26276815/my-chrome-extension-popup-opens-after-a-few-seconds-its-slow-compared-to-other

**Comment by foray1010** [comment] 2015-08-07 16:04
tried, it is very similar for me. My computer is not fast, I am using Chromebook C720.
Do you need to take 1 - 2 seconds to load PmB?

**Comment by MartinLichtblau** [comment] 2015-08-07 17:18
Yes around 1-2sec.
It also shows the loading circle around the mouse. Some extensions open instantly and really smooth, like the google translate extension.
Perhaps the trick above works. 
Or perhaps there is some function in your js which slows done the whole extension. The number of bookmarks is not the problem (I testet that), it loads equally fast no matter how many bookmarks you have, which I find kinda strange... Are you making a harddisk call, network call or some stuff like this, which is not async? [Or do you have some synchronous function in your code?](https://developer.chrome.com/extensions/overview)
So try out to show the html first and after that you can run your other functionality.

**Comment by foray1010** [comment] 2015-08-08 00:09
Yes, I do it on purpose. See desc: `- No background running application, save your memory and privacy!`

I do put performance in my mind in the very first moment, you can see that in https://github.com/foray1010/Popup-my-Bookmarks/blob/master/html/popup.jade I load all the JS after DOM is done, and no network call at all.

So, I think the problem is, chrome needs time to fetch the js/css/html/locales files from hard disk every time. But in my computer, it just takes about 300ms! Could be I am using SSD.

So, I think I need your computer for testing, could you help me to:
1. Follow http://stackoverflow.com/questions/26276815/my-chrome-extension-popup-opens-after-a-few-seconds-its-slow-compared-to-other , you can modify PmB directly in the user data of Chrome. Just make sure you reload PmB in extension page. See if it is faster
2. Right click PmB, Inspect Popup, Click the network tab, select option `Preserve Log`, Click the console tab, try and fire `location.reload()`, Click back to network tab, screen cap to me.

Thanks!

**Comment by MartinLichtblau** [comment] 2015-08-08 07:32
There's no difference in speed with the change mentioned in the post, when doing a location.reload(). And I see now visual improvement in speed. 

But one thing is sure, when doing the location.reload() is much loads the Popup much faster than when you open the popup by hand. So the response time shown in the network monitor doesn't represent the real speed.
Furthermore I did the same test with the google translator extension and it has a much higher responsetime in the network monitor altough it is much faste in reality (After first load/click on it). When you click on the translator for the first time it's slow but after that it's super responsive!
 
The console states the following `
`` location.reload()
undefined
Navigated to chrome-extension://mppflflkbbafeopeoeigkbbdjdbeifni/popup.html `` 

Here's the network tab before the change mentioned in the link above:
![image](https://cloud.githubusercontent.com/assets/4956334/9149514/32647dfa-3dae-11e5-933f-131d2eb65cbc.png)

Here's the network tab after the change: 
![image](https://cloud.githubusercontent.com/assets/4956334/9149512/fa59f49e-3dad-11e5-8164-f658289ff22a.png)

**Comment by MartinLichtblau** [comment] 2015-08-08 07:57
How is it possible to cache the PMB, instead of loading it every time?

**Comment by foray1010** [comment] 2015-08-08 17:26
Arr, it is because PmB can `Access your data on all websites`, if it is loaded in the background, people may get suspicious...
Normally, PmB will eat up to 50~MB RAM, it maybe a trouble for computer with 1-2GB RAM. I don't know, but there are at least two guys commented on this feature as a good one.

So, I prefer to make it as an option, I will see if I can do it.

**Comment by foray1010** [comment] 2015-08-08 17:42
Wow, never heard of HTML5 cache, will try.

Thanks for the testing. So, I think the bottleneck is loading files from harddisk. Can I confirm if you are using traditional HDD instead of SSD?

**Comment by MartinLichtblau** [comment] 2015-08-08 21:42
No, I have an SDD in my notebook.

**Comment by tfoxy** [comment] 2015-08-09 00:13
A background page can be closed at any moment using `window.close()`.

So you can add the option to load the popup into the background. When the option is unchecked, you can close the background page when it is initialized.

The downside is that the background page is always loaded when the browser starts.

**Comment by foray1010** [comment] 2015-08-09 05:25
@tfoxy That's a good way! The downside is almost ignorable!

![Challenge Accepted](http://vignette2.wikia.nocookie.net/animaljam/images/d/d2/Challenge-accepted.png)

**Comment by MartinLichtblau** [comment] 2015-10-31 21:16
I just found sth. out.
When I click on the PMB icon, the windows loading icon shows up and it takes some time till the bookmarks show up.
But when I have the PMB options site open, no loading icon shows up and the bookmarks show up instantly. 
Somwhow weird!?

**Comment by foray1010** [comment] 2015-11-01 07:12
you are right, it is because when option page is opened, PMB is cached in memory, so it will load faster
tfoxy' solution will do the same

**Comment by MartinLichtblau** [comment] 2015-11-01 09:14
Ahh, now I get it, ok!
Would be great if you could implement this option :+1: 
Thanks for your work :)

**Comment by foray1010** [comment] 2018-05-09 02:05
@alon91 no matter how fast this extension can be made, it is hard to guarantee your use case will work, there are limitations on how fast Chrome can load the extension.
I suggest adding a keyboard for searching in address bar may be a better suit for your use case
for example, type `b your_search_query` and search result will be shown under the address bar
what do you think?

**Comment by mrbig033** [comment] 2018-05-19 01:55
Could you at least allow disabling the fades?

**Comment by foray1010** [comment] 2018-05-19 13:46
@mrbig033 what fades you mean? there is no fades animation in PmB

**Comment by foray1010** [comment] 2018-05-20 01:01
@mrbig033 this animation is managed by the operating system you are using. It is beyond my control

**Comment by mrbig033** [comment] 2018-05-20 16:31
It's unlikely. I'm using MX Linux the i3wm. i3 is a tiling manager, which means zero fluff. But I guess it could be a Chrome thing?

**Comment by alon91** [comment] 2018-05-22 04:16
FYI: there's an extension with very similar capabilities that loads waaaay faster than PMB --
https://chrome.google.com/webstore/detail/bookmark-express/edgcdcdceojjbiebdbgmacecicaknjih

**Comment by alon91** [comment] 2018-07-19 23:36
Big apologies for nagging but performance has taken a turn for the worse on my machine. It sometimes takes 2+ seconds for the pop-up window to appear.

Any plans to investigate speeding up the panel opening the way it works in the extension I linked to in my May 21 comment?

I use this extension dozens of times a day so an improvement here would make a massive difference in my productivity. Many thanks in advance!!

**Comment by foray1010** [comment] 2018-07-20 02:26
@alon91, the hack this extension used is the same as MartinLichtblau suggested above

I temporarily do not spend much time on this extension, I will see if I have time to add this hack this weekend

**Comment by foray1010** [comment] 2018-07-22 11:47
@MartinLichtblau @alon91 fixed in 5.2.0, please take a look if it works for u

**Closed by foray1010** 2018-07-22 11:47 UTC
Labels: Challenge Accepted, Feature Request

**Comment by alon91** [comment] 2018-07-22 20:04
This. update. is. AMAZING!

Thank you so much for adding this feature. The extension is so much more powerful now. I appreciate your hard work here!
