### ISSUE TITLE
Display issue under windows 10

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [foray1010/Popup-my-Bookmarks#123] opened 2017-09-15 05:02 UTC
when open the menu, chrome start to flash black across the screen. happens both when open general menu and sub-folder menu. when a menu is opened, it no more flashes.

**Comment by foray1010** [comment] 2018-02-20 13:14
as I do not have a windows 10 device, does this issue still exist? can anyone confirm?

**Comment by silou** [comment] 2019-03-28 05:30
Yes, I got it , unable to acces only the 1st tab of config (Named Général) , others tabs work well.

**Comment by foray1010** [comment] 2019-03-28 06:39
@silou seems yours is about options page? if you cannot access General page, how can you access to other tabs?

**Comment by silou** [comment] 2019-03-29 15:00
Hi,

Thanks for answering so fast: I made you a  little GIF to see that in action. It moves faster than the GIF in real life. 1st <Config Tab> not and all other things seems OK, I think : https://drive.google.com/open?id=1c5bjWNCfILaiOeIX20hwDhxU3c6dNCj1

**Comment by foray1010** [comment] 2019-03-30 03:25
@silou seems the problem is the description in french is too long. I cannot reproduce in macos but I have published `5.3.2` which extended the options page width, see if it fixes your problem

**Comment by silou** [comment] 2019-03-30 10:55
@foray1010 ,

Thanks, it seems to be working fine for me.
Have a good day.

**Comment by foray1010** [comment] 2019-03-30 14:30
nice, I am closing this issue since no further info from original reporter

**Closed by foray1010** 2019-03-30 14:30 UTC
